#ifndef USER_ACTIVITY_NATIVE_NODE_NODULE
#define USER_ACTIVITY_NATIVE_NODE_NODULE

#include <nan.h>

NAN_METHOD(AsyncSpyActive);
NAN_METHOD(AsyncSpyUnactive);

#endif  // USER_ACTIVITY_NATIVE_NODE_NODULE